# Generated by Django 3.1.5 on 2021-01-14 15:39

from django.db import migrations, models
import myApp.models
import myApp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=myApp.storage.OverwriteStorage(), upload_to=myApp.models.User.get_upload_dir),
        ),
    ]
